spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/DOCAL
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show=sql: false
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
  mvc:
    view:
      prefix: /templates/
      suffix: .html
server:
  port: 8080
